sudo: required
services: docker
language: bash

branches:
  only:
    - master

env:
  global:
    - DOCKER_REPO=siji

  matrix:
    - NAME=shadowsocks
    - NAME=polipo
    - NAME=privoxy

before_script:
  - docker build -t $DOCKER_REPO/$NAME:latest $NAME

script:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO/$NAME:latest; fi
